// Code generated by mockery v2.15.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	internaldomain "github.com/willkoerich/rock-challenge/internal/domain"
)

// TransferRepository is an autogenerated mock type for the TransferRepository type
type TransferRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *TransferRepository) GetAll(ctx context.Context) ([]internaldomain.Transfer, error) {
	ret := _m.Called(ctx)

	var r0 []internaldomain.Transfer
	if rf, ok := ret.Get(0).(func(context.Context) []internaldomain.Transfer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internaldomain.Transfer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAccountOriginID provides a mock function with given fields: ctx, accountOriginID
func (_m *TransferRepository) GetByAccountOriginID(ctx context.Context, accountOriginID int) ([]internaldomain.Transfer, error) {
	ret := _m.Called(ctx, accountOriginID)

	var r0 []internaldomain.Transfer
	if rf, ok := ret.Get(0).(func(context.Context, int) []internaldomain.Transfer); ok {
		r0 = rf(ctx, accountOriginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internaldomain.Transfer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, accountOriginID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransferRepository) GetByID(ctx context.Context, id int) (internaldomain.Transfer, error) {
	ret := _m.Called(ctx, id)

	var r0 internaldomain.Transfer
	if rf, ok := ret.Get(0).(func(context.Context, int) internaldomain.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(internaldomain.Transfer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, transfer
func (_m *TransferRepository) Save(ctx context.Context, transfer internaldomain.Transfer) (internaldomain.Transfer, error) {
	ret := _m.Called(ctx, transfer)

	var r0 internaldomain.Transfer
	if rf, ok := ret.Get(0).(func(context.Context, internaldomain.Transfer) internaldomain.Transfer); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(internaldomain.Transfer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, internaldomain.Transfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransferRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransferRepository creates a new instance of TransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransferRepository(t mockConstructorTestingTNewTransferRepository) *TransferRepository {
	mock := &TransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
