// Code generated by mockery v2.15.0. DO NOT EDIT.

package crypto

import mock "github.com/stretchr/testify/mock"

// SecurePasswordService is an autogenerated mock type for the SecurePasswordService type
type SecurePasswordService struct {
	mock.Mock
}

// Compare provides a mock function with given fields: hashedPassword, password
func (_m *SecurePasswordService) Compare(hashedPassword []byte, password []byte) error {
	ret := _m.Called(hashedPassword, password)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: password, cost
func (_m *SecurePasswordService) Generate(password []byte, cost int) ([]byte, error) {
	ret := _m.Called(password, cost)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte, int) []byte); ok {
		r0 = rf(password, cost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, int) error); ok {
		r1 = rf(password, cost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSecurePasswordService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecurePasswordService creates a new instance of SecurePasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecurePasswordService(t mockConstructorTestingTNewSecurePasswordService) *SecurePasswordService {
	mock := &SecurePasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
