// Code generated by mockery v2.15.0. DO NOT EDIT.

package crypto

import mock "github.com/stretchr/testify/mock"

// SecurePasswordService is an autogenerated mock type for the SecurePasswordService type
type SecurePasswordService struct {
	mock.Mock
}

// Compare provides a mock function with given fields: hashedPassword, password
func (_m *SecurePasswordService) Compare(hashedPassword string, password string) error {
	ret := _m.Called(hashedPassword, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: password
func (_m *SecurePasswordService) Generate(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSecurePasswordService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecurePasswordService creates a new instance of SecurePasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecurePasswordService(t mockConstructorTestingTNewSecurePasswordService) *SecurePasswordService {
	mock := &SecurePasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
